# Generated by Django 5.2.15 on 2026-06-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('message', models.TextField(verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='主题')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件发送',
                'ordering': ['-created_at'],
            },
        ),
    ]
