# Generated by Django 5.2.15 on 2026-06-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardsaying',
            table='boardsaying',
        ),
        migrations.AlterModelTable(
            name='emailsending',
            table='emailsending',
        ),
    ]
